repos:
#  - repo: https://github.com/jumanjihouse/pre-commit-hooks
#    rev: 3.0.0
#    hooks:
#    - id: markdownlint

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check

  - repo: "https://github.com/domluna/JuliaFormatter.jl"
    rev: "v1.0.35"
    hooks:
      - id: "julia-formatter"

  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.11.0
    hooks:
      - id: bibtex-tidy
        args: [ '--months', '--space=4', '--sort',
                '--duplicates', '--strip-enclosing-braces', '--sort-fields' ]
