name: conda_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  # - slepc4py=*=complex*
  - numpy
  - pip:
      - matplotlib
      - scipy
      - shapely
      - pygmsh
      - meshio
      - tqdm
      - git+https://github.com/HelgeGehring/scikit-fem.git@add-utils-mpc
      - git+https://github.com/HelgeGehring/femwell.git