name: conda_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - mesa-libgl-devel-cos7-x86_64 # for gmsh
  - meshio
  - matplotlib
  - shapely
  - slepc4py=*=complex*
  - scipy
  - pip:
      - pygmsh
      - git+https://github.com/kinnala/scikit-fem.git
      - git+https://github.com/HelgeGehring/femwell.git