name: conda_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - slepc4py=*=complex*
  - numpy
  - pip:
      - matplotlib
      - scipy
      - shapely
      - pygmsh
      - meshio
      - tqdm
      - scikit-fem >=1.2.3
      - git+https://github.com/HelgeGehring/femwell.git
