name: conda_env
channels:
  - conda-forge
dependencies:
  - python
  - gmsh
  - python-gmsh
  - matplotlib
  - shapely
  - slepc4py=*=complex*
  - pip:
      - git+https://github.com/kinnala/scikit-fem.git
      - git+https://github.com/HelgeGehring/femwell.git