name: conda_env
channels:
  - defaults
dependencies:
  - python
  - pip
  - conda-forge::gmsh
  - conda-forge::python-gmsh
  - conda-forge::meshio
  - conda-forge::matplotlib
  - conda-forge::shapely
  - conda-forge::scipy
  - conda-forge::slepc4py=*=complex*
  - pip:
      - git+https://github.com/kinnala/scikit-fem.git
      - git+https://github.com/HelgeGehring/femwell.git