name: conda_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - slepc4py=*=complex*
  - pip:
      - numpy
      - matplotlib
      - scipy
      - shapely
      - pygmsh
      - meshio
      - git+https://github.com/kinnala/scikit-fem.git
      - git+https://github.com/HelgeGehring/femwell.git