name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: |
          sudo apt-get install -y libglu1-mesa
          poetry install --no-interaction --no-root
          source $VENV
          pip install --upgrade git+https://github.com/kinnala/scikit-fem.git
      - name: Install slepc4py
        run: |
          source $VENV
          export PETSC_CONFIGURE_OPTIONS="--with-scalar-type=complex"
          pip install petsc
          pip install petsc4py
          pip install slepc
          pip install slepc4py
      - name: Lint with flake8
        run: |
          source $VENV
          # stop the build if there are Python syntax errors or undefined names
          flake8 femwell --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 femwell --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      #      - name: Test with pytest
      #        run: |
      #          source .venv/bin/activate
      #          pytest
      - name: Build package
        run: |
          source $VENV
          poetry build