name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"
          args:
            "--exit-zero"
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: |
          sudo apt-get install -y libglu1-mesa
          poetry install --no-interaction --no-root
          source $VENV
          pip install --upgrade git+https://github.com/kinnala/scikit-fem.git
      - name: Install slepc4py
        run: |
          source $VENV
          export PETSC_CONFIGURE_OPTIONS="--with-scalar-type=complex"
          pip install petsc
          pip install petsc4py
          pip install slepc
          pip install slepc4py
      - name: Build package
        run: |
          source $VENV
          poetry build
