name: docs

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: env
            use-mamba: true
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: false
          installer-parallel: true
      - name: Install dependencies
        run: |
          sudo apt-get install -y libglu1-mesa
          mamba install slepc4py=*=complex* -y
          pip install jupyter-book
          pip install --upgrade jupytext
          pip install sphinx=="5.3.0"
          pip install docutils=="0.17.1"
          pip uninstall -y scikit-fem
          pip install --upgrade git+https://github.com/kinnala/scikit-fem.git
          pip list
      - name: Make docs
        run: |
          jupyter-book build docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/_build/html/'

  deploy:
    if: ${{ github.repository == 'HelgeGehring/femwell' }} # skip for forks
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  #trigger-binder-build:
  #  runs-on: [ubuntu-latest]
  #  steps:
  #    - uses: s-weigand/trigger-mybinder-build@v1
  #      with:
  #        target-repo: HelgeGehring/femwell
  #        target-state: HEAD
  #        service-name: gh
  #        debug: true
